project:
  type: book
  output-dir: docs

book:
  title: An example ageing criteria report
  subtitle: Pristipomoides zonatus
  date: January 2023
  downloads: [pdf, docx]
  author:
  - name: Eva Schemmel
    affiliations:
      - id: PIFSC-LHP
        name: Pacific Islands Fisheries Science Center
        department: Life History Program
        address:
          - 1845 Wasp Boulevard
          - Honolulu, HI 96818
  - name: Kristen Dahl
    affiliations:
      - id: PIFSC-LHP
        name: Pacific Islands Fisheries Science Center
        department: Life History Program
        address:
          - 1845 Wasp Boulevard
          - Honolulu, HI 96818
  chapters:
    - index.qmd
    - text/Introduction.qmd
    - text/Methods2.qmd
    - text/Results3.qmd
    - text/Discussion4.qmd
    - text/references.qmd

  site-url: https://nmfs-opensci.github.io/NOAA-tech-memo-template/
  repo-url: https://github.com/nmfs-opensci/NOAA-tech-memo-template
  repo-actions: [edit, source, issue]
  search: true

bibliography:
  - text/references.bib

execute:
  echo: false
  code-overflow: wrap
  freeze: auto

format:
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"

metadata-files:
  - _frontmatter.yml
  
